# Generated by Django 5.1.6 on 2025-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
